# Generated by Django 3.0 on 2020-02-24 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionPedidos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='tfno',
            field=models.CharField(max_length=9),
        ),
    ]
